services:
  web:
    build: .
    container_name: auth_service_web
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - UPSTASH_REDIS_REST_URL=${UPSTASH_REDIS_REST_URL}
      - UPSTASH_REDIS_REST_TOKEN=${UPSTASH_REDIS_REST_TOKEN}
    depends_on:
      - db
      # - redis

  db:
    image: postgres:15
    container_name: auth_service_db
    restart: always
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   container_name: auth_service_redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data: {}
